[project]
name = "agent-math-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.1.0",
    "openai>=2.16.0",
    "rich>=14.3.1",
]
